### ISSUE TITLE
reimplement zmq data payloads

### ISSUE THREAD

**Issue by k323r** [flucto-gmbh/motion-sensor-box#51] opened 2023-02-06 10:29 UTC
Currently, data from primary and secondary producers is communicated as pickled lists on zmq. This requires knowledge about the data present in the lists. However, a self-describing data format would greatly enhance compatability and processability of the data. Thus, instead of sending pickled lists of data, data should be packed into dictionaries, where the keys describe each data point.

**Comment by pacjac** [comment] 2023-03-23 10:50
Duplicate of #53

**Closed by pacjac** 2023-03-23 10:50 UTC
Labels: enhancement
